version: 2.1

orbs:
  node: circleci/node@5.1.0
  slack: circleci/slack@4.12.0

jobs:
  test:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Backend Tests
          command: |
            chmod +x node_modules/.bin/jest
            npm test
      - run:
          name: Run Frontend Tests
          command: |
            cd frontend
            npm install
            npm test -- --watchAll=false
      - store_test_results:
          path: test-results

  build:
    docker:
      - image: cimg/node:18.16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Frontend
          command: |
            cd frontend
            npm install
            npm run build
      - store_artifacts:
          path: frontend/build
          destination: build

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test
      - build:
          requires:
            - test